name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      -name: pulling git repo
      uses: actions/checkout@v2
      -name: say his to sriram
      run: echo "hello sriram"
